---

- name: Crash on other OS other than Suse based
  fail: msg="Not a Suse based Distro."
  when: ansible_os_family != "Suse"

- name: Repositories for Leap
  include: "repos.yml"
  vars:
    suse_repo_factory: "{{ suse_repo_default }}"
  when: ansible_distribution == "openSUSE Leap"

- name: Repositories for Tumbleweed
  include: "repos.yml"
  vars:
    suse_repo_factory: openSUSE_Factory
  when: ansible_distribution == "openSUSE Tumbleweed"
